const battle = [
   {id: 0, name: 'Select Battle', length: 0, startDigit: 0},
   { id: 1, name: 'Pilot Battle', length: 12, startDigit: 1},
   { id: 2, name: 'Visibility', length: 6, startDigit: 13},
   { id: 3, name: 'Cursor', length: 2, startDigit: 18},
   { id: 4, name: 'Display', length: 8, startDigit: 21},
   { id: 5, name: 'Inline', length: 2, startDigit: 29},
   { id: 6, name: 'Conic', length: 2, startDigit: 31},
   { id: 7, name: 'Backface', length: 9, startDigit: 33},
   { id: 8, name: 'Transition', length: 3, startDigit: 42},
   { id: 9, name: 'Margin', length: 2, startDigit: 45},
   { id: 10, name: 'Block', length: 6, startDigit: 47},
   { id: 11, name: 'Overflow', length: 8, startDigit: 53},
   { id: 12, name: 'Blend', length: 8, startDigit: 61},
   { id: 13, name: 'Clip', length: 8, startDigit: 69},
   { id: 14, name: 'zIndex', length: 4, startDigit: 77},
   { id: 15, name: 'Filter', length: 8, startDigit: 81},
   { id: 16, name: 'Aspect', length: 8, startDigit: 89},
   { id: 17, name: 'Christmas', length: 4, startDigit: 97},
   { id: 18, name: 'Anime', length: 8, startDigit: 101},
   { id: 19, name: 'Spacing', length: 8, startDigit: 109},
   { id: 20, name: 'Hover', length: 8, startDigit: 117},
   { id: 21, name: 'Rotate', length: 8, startDigit: 125},
]
let dir = '/Snippets/CSSBattle/Individual/'
const play = [
   { id: 0,   name: 'Select Level', parentId: 0, url: 'default.html'},
   { id: 1,   name: 'Simply Square', parentId: 1, url: `${dir}01-Simply-Square.html`},
   { id: 2,   name: 'Carrom', parentId: 1, url: `${dir}02-Carrom.html`},
   { id: 3,   name: 'Push Button', parentId: 1,  url: `${dir}03-Push-Button.html` },
   { id: 4,   name: 'Ups and Downs', parentId: 1,  url: `${dir}04-Ups-and-Downs.html` },
   { id: 5,   name: 'Acid Rain', parentId: 1,  url: `${dir}05-Acid-Rain.html` },
   { id: 6,   name: 'Missing Slice', parentId: 1,  url: `${dir}06-Missing-Slice.html` },
   { id: 7,   name: 'Leafy Trail', parentId: 1,  url: `${dir}07-Leafy-Trail.html` },
   { id: 8,   name: 'Forking Crazy', parentId: 1,  url: `${dir}08-Forking-Crazy.html` },
   { id: 9,   name: 'Tesseract', parentId: 1,  url: `${dir}09-Tesseract.html` },
   { id: 10,  name: 'Cloaked Spirits', parentId: 1,  url: `${dir}10-Cloaked-Spirits.html` },
   { id: 11,  name: 'Eye of Sauron', parentId: 1,  url: `${dir}11-Eye-of-Sauron.html` },
   { id: 12,  name: 'Wiggly Moustache', parentId: 1,  url: `${dir}12-Wiggly-Moustache.html` },
   { id: 13,  name: 'Totally Triangle', parentId: 2,  url: `${dir}13-Totally-Triangle.html` },  
   { id: 14,  name: 'Web Maker Logo', parentId: 2,  url: `${dir}14-Web-Maker-Logo.html` },
   { id: 15,  name: 'Overlap', parentId: 2,  url: `${dir}15-Overlap.html` },
   { id: 16,  name: 'Eye of the Tiger', parentId: 2,  url: `${dir}16-Eye-of-the-Tiger.html` },
   { id: 17,  name: 'Fidget Spinner', parentId: 2,  url: `${dir}17-Fidget-Spinner.html` },
   { id: 18,  name: 'Matrix', parentId: 2,  url: `${dir}18-Matrix.html` },
   { id: 19,  name: 'Cube', parentId: 3,  url: `${dir}19-Cube.html` },
   { id: 20,  name: 'Ticket', parentId: 3,  url: `${dir}20-Ticket.html` },
   { id: 21,  name: 'Sitepoint Logo', parentId: 4,  url: `${dir}21-Sitepoint-Logo.html` },
   { id: 22,  name: 'Cloud', parentId: 4,  url: `${dir}22-Cloud.html` },
   { id: 23,  name: 'Boxception', parentId: 4,  url: `${dir}23-Boxception.html` },
   { id: 24,  name: 'Switches', parentId: 4,  url: `${dir}24-Switches.html` },
   { id: 25,  name: 'Blossom', parentId: 4,  url: `${dir}25-Blossom.html` },
   { id: 26,  name: 'Smiley', parentId: 4,  url: `${dir}26-Smiley.html` },
   { id: 27,  name: 'Lock Up', parentId: 4,  url: `${dir}27-Lock-Up.html` },
   { id: 28,  name: 'Cups and Balls', parentId: 4,  url: `${dir}28-Cups-and-Balls.html` },
   { id: 29,  name: 'Suffocate', parentId: 5,  url: `${dir}29-Suffocate.html` }, 
   { id: 30,  name: 'Horizon', parentId: 5,  url: `${dir}30-Horizon.html` },
   { id: 31,  name: 'Equals', parentId: 6,  url: `${dir}31-Equals.html` }, 
   { id: 32,  name: 'Band Aid', parentId: 6,  url: `${dir}32-Band-Aid.html` },
   { id: 33,  name: 'Birdie', parentId: 7,  url: `${dir}33-Birdie.html` },
   { id: 34,  name: 'Christmas Tree', parentId: 7,  url: `${dir}34-Christmas-Tree.html` },
   { id: 35,  name: 'Ice Cream', parentId: 7,  url: `${dir}35-Ice-Cream.html` },
   { id: 36,  name: 'Interleaved', parentId: 7,  url: `${dir}36-Interleaved.html` },
   { id: 37,  name: 'Tunnel', parentId: 7,  url: `${dir}37-Tunnel.html` },
   { id: 38,  name: 'Not Simply Square', parentId: 7,  url: `${dir}38-Not-Simply-Square.html` },
   { id: 39,  name: 'Sunset', parentId: 7,  url: `${dir}39-Sunset.html` },
   { id: 40,  name: 'Letter B', parentId: 7,  url: `${dir}40-Letter-B.html` },
   { id: 41,  name: 'Fox Head', parentId: 7,  url: `${dir}41-Fox-Head.html` },
   { id: 42,  name: 'Baby', parentId: 8,  url: `${dir}42-Baby.html` },
   { id: 43,  name: 'Wrench', parentId: 8,  url: `${dir}43-Wrench.html` },
   { id: 44,  name: 'Stripes', parentId: 8,  url: `${dir}44-Stripes.html` },
   { id: 45,  name: 'Magical Tree', parentId: 9,  url: `${dir}45-Magical-Tree.html` },
   { id: 46,  name: 'Mountains', parentId: 9,  url: `${dir}46-Mountains.html` },
   { id: 47,  name: 'Corona virus', parentId: 10, url: `${dir}47-Corona-virus.html` },
   { id: 48,  name: 'Wash Your hands', parentId: 10, url: `${dir}48-Wash-Your-hands.html` },
   { id: 49,  name: 'Stay at Home', parentId: 10, url: `${dir}49-Stay-at-Home.html` },
   { id: 50,  name: 'Use Hand Sanitizer', parentId: 10, url: `${dir}50-Use-Hand-Sanitizer.html` },
   { id: 51,  name: 'Wear a Mask', parentId: 10, url: `${dir}51-Wear-a-Mask.html` },
   { id: 52,  name: 'Break the Chain', parentId: 10, url: `${dir}52-Break-the-Chain.html` },
   { id: 53,  name: 'Pastel Logo', parentId: 11, url: `${dir}53-Pastel-Logo.html` },
   { id: 54,  name: 'Black Lives Matt', parentId: 11, url: `${dir}54-Black-Lives-Matt.html` },
   { id: 55,  name: 'Windmill', parentId: 11, url: `${dir}55-Windmill.html` },
   { id: 56,  name: 'Skull', parentId: 11, url: `${dir}56-Skull.html` },
   { id: 57,  name: 'Pillars', parentId: 11, url: `${dir}57-Pillars.html` },
   { id: 58,  name: 'Rose', parentId: 11, url: `${dir}58-Rose.html` },
   { id: 59,  name: 'Earth', parentId: 11, url: `${dir}59-Earth.html` },
   { id: 60,  name: 'Evil Triangles', parentId: 11, url: `${dir}60-Evil-Triangles.html` },
   { id: 61,  name: 'ImprovMX', parentId: 12, url: `${dir}61-ImprovMX.html` },
   { id: 62,  name: 'Sunset', parentId: 12, url: `${dir}62-Sunset.html` },
   { id: 63,  name: 'Command Key', parentId: 12, url: `${dir}63-Command-Key.html` },
   { id: 64,  name: 'Door Knob', parentId: 12, url: `${dir}64-Door-Knob.html` },
   { id: 65,  name: 'Max Volume', parentId: 12, url: `${dir}65-Max-Volume.html` },
   { id: 66,  name: 'Batmicky', parentId: 12, url: `${dir}66-Batmicky.html` },
   { id: 67,  name: 'Video Reel', parentId: 12, url: `${dir}67-Video-Reel.html` },
   { id: 68,  name: 'Bell', parentId: 12, url: `${dir}68-Bell.html` },
   { id: 69,  name: 'PushOwl', parentId: 13, url: `${dir}69-PushOwl.html` },
   { id: 70,  name: 'Froggy', parentId: 13, url: `${dir}70-Froggy.html` },
   { id: 71,  name: 'Elephant', parentId: 13, url: `${dir}71-Elephant.html` },
   { id: 72,  name: 'Sheep', parentId: 13, url: `${dir}72-Sheep.html` },
   { id: 73,  name: 'Happy Tiger', parentId: 13, url: `${dir}73-Happy-Tiger.html` },
   { id: 74,  name: 'Danger Noodle', parentId: 13, url: `${dir}74-Danger-Noodle.html` },
   { id: 75,  name: 'Hippo', parentId: 13, url: `${dir}75-Hippo.html` },
   { id: 76,  name: 'Beeee', parentId: 13, url: `${dir}76-Beeee.html` },
   { id: 77,  name: 'Notes', parentId: 14, url: `${dir}77-Notes.html` },
   { id: 78,  name: 'Ukelele', parentId: 14, url: `${dir}78-Ukelele.html` },
   { id: 79,  name: 'Tambourine', parentId: 14, url: `${dir}79-Tambourine.html` },
   { id: 80,  name: 'Piano', parentId: 14, url: `${dir}80-Piano.html` },
   { id: 81,  name: 'Odoo', parentId: 15, url: `${dir}81-Odoo.html` },
   { id: 82,  name: 'Diamond Cut', parentId: 15, url: `${dir}82-Diamond-Cut.html` },
   { id: 83,  name: 'Supernova', parentId: 15, url: `${dir}83-Supernova.html` },
   { id: 84,  name: 'Junction', parentId: 15, url: `${dir}84-Junction.html` },
   { id: 85,  name: 'Pythagoras', parentId: 15, url: `${dir}85-Pythagoras.html` },
   { id: 86,  name: 'Stairway', parentId: 15, url: `${dir}86-Stairway.html` },
   { id: 87,  name: 'Building Blocks', parentId: 15, url: `${dir}87-Building-Blocks.html` },
   { id: 88,  name: 'Tight Corner', parentId: 15, url: `${dir}88-Tight-Corner.html` },
   { id: 89,  name: 'Summit', parentId: 16, url: `${dir}89-Summit.html` },
   { id: 90,  name: 'Eclipse', parentId: 16, url: `${dir}90-Eclipse.html` },
   { id: 91,  name: 'Relection', parentId: 16, url: `${dir}91-Relection.html` },
   { id: 92,  name: 'Squeeze', parentId: 16, url: `${dir}92-Squeeze.html` },
   { id: 93,  name: 'Greatwall', parentId: 16, url: `${dir}93-Greatwall.html` },
   { id: 94,  name: 'Ripples', parentId: 16, url: `${dir}94-Ripples.html` },
   { id: 95,  name: 'PokeBall', parentId: 16, url: `${dir}95-PokeBall.html` },
   { id: 96,  name: 'Mandala', parentId: 16, url: `${dir}96-Mandala.html` },
   { id: 97,  name: 'Snowman', parentId: 17, url: `${dir}97-Snowman.html` },
   { id: 98,  name: 'Candle', parentId: 17, url: `${dir}98-Candle.html` },
   { id: 99,  name: 'Giftbox', parentId: 17, url: `${dir}99-Giftbox.html` },
   { id: 100, name: 'CssBattle', parentId: 17, url: `${dir}100-CssBattle.html` },
   { id: 101, name: 'Sharingan', parentId: 18, url: `${dir}101-Sharingan.html` },
   { id: 102, name: 'One Piece', parentId: 18, url: `${dir}102-One-Piece.html` },
   { id: 103, name: 'SuperSaiyan', parentId: 18, url: `${dir}103-SuperSaiyan.html` },
   { id: 104, name: 'Amagakure', parentId: 18, url: `${dir}104-Amagakure.html` },
   { id: 105, name: 'Ryuk', parentId: 18, url: `${dir}105-Ryuk.html` },
   { id: 106, name: `Ryuk's Apple`, parentId: 18, url: `${dir}106-Ryuks-Apple.html` },
   { id: 107, name: 'Sealing Wand', parentId: 18, url: `${dir}107-Sealing-Wand.html` },
   { id: 108, name: 'Clow Card', parentId: 18, url: `${dir}108-Clow-Card.html` },
   { id: 109, name: 'Curtain', parentId: 19, url: `${dir}109-Curtain.html` },
   { id: 110, name: 'Sunrays', parentId: 19, url: `${dir}110-Sunrays.html` },
   { id: 111, name: 'Rain Drops', parentId: 19, url: `${dir}111-Rain-Drops.html` },
   { id: 112, name: 'Chevron', parentId: 19, url: `${dir}112-Chevron.html` },
   { id: 113, name: 'Black Light', parentId: 19, url: `${dir}113-Black-Light.html` },
   { id: 114, name: 'Negative Box', parentId: 19, url: `${dir}114-Negative-Box.html` },
   { id: 115, name: 'Droplet', parentId: 19, url: `${dir}115-Droplet.html` },
   { id: 116, name: 'Headphones', parentId: 19, url: `${dir}116-Headphones.html` },
   { id: 117, name: 'Arineo', parentId: 20, url: `${dir}117-Arineo.html` },
   { id: 118, name: 'Donkey Kong', parentId: 20, url: `${dir}118-Donkey-Kong.html` },
   { id: 119, name: 'Pacman', parentId: 20, url: `${dir}119-Pacman.html` },
   { id: 120, name: 'Tank ', parentId: 20, url: `${dir}120-Tank.html` },
   { id: 121, name: 'DuckHunt', parentId: 20, url: `${dir}121-DuckHunt.html` },
   { id: 122, name: 'Tetris', parentId: 20, url: `${dir}122-Tetris.html` },
   { id: 123, name: 'Snake', parentId: 20, url: `${dir}123-Snake.html` },
   { id: 124, name: 'Space Invaders', parentId: 20, url: `${dir}124-Space-Invaders.html` },
   { id: 125, name: 'Root Learn', parentId: 21, url: `${dir}125-Root-Learn.html` },
   { id: 126, name: 'Letter A', parentId: 21, url: `${dir}126-Letter-A.html` },
   { id: 127, name: 'Letter I', parentId: 21, url: `${dir}127-Letter-I.html` },
   { id: 128, name: 'Letter N', parentId: 21, url: `${dir}128-Letter-N.html` },
   { id: 129, name: 'Letter B', parentId: 21, url: `${dir}129-Letter-B.html` },
   { id: 130, name: 'Letter O', parentId: 21, url: `${dir}130-Letter-O.html` },
   { id: 131, name: 'Letter W', parentId: 21, url: `${dir}131-Letter-W.html` },
   { id: 132, name: 'Letter S', parentId: 21, url: `${dir}132-Letter-S.html` },













]
export { battle, play }