const battle = [
   {id: 0, name: 'Select Battle', length: 0, startDigit: 0},
   { id: 1, name: 'Pilot Battle', length: 12, startDigit: 1},
   { id: 2, name: 'Visibility', length: 6, startDigit: 13},
   { id: 3, name: 'Cursor', length: 2, startDigit: 18},
   { id: 4, name: 'Display', length: 8, startDigit: 21},
   { id: 5, name: 'Inline', length: 2, startDigit: 29},
   { id: 6, name: 'Conic', length: 2, startDigit: 31},
   { id: 7, name: 'Backface', length: 9, startDigit: 33},
   { id: 8, name: 'Transition', length: 3, startDigit: 42},
   { id: 9, name: 'Margin', length: 2, startDigit: 45},
   { id: 10, name: 'Block', length: 6, startDigit: 47},
   { id: 11, name: 'Overflow', length: 8, startDigit: 53},
   { id: 12, name: 'Blend', length: 8, startDigit: 61},
   { id: 13, name: 'Clip', length: 8, startDigit: 69},
   { id: 14, name: 'zIndex', length: 4, startDigit: 77},
   { id: 15, name: 'Filter', length: 8, startDigit: 81},
   { id: 16, name: 'Aspect', length: 8, startDigit: 89},
   { id: 17, name: 'Christmas', length: 4, startDigit: 97},
   { id: 18, name: 'Anime', length: 8, startDigit: 101},
   { id: 19, name: 'Spacing', length: 8, startDigit: 109},
   { id: 20, name: 'Hover', length: 8, startDigit: 117},
   { id: 21, name: 'Rotate', length: 8, startDigit: 125},
]
let dir = '/Snippets/CSSBattle/Individual/'
const play = [
   { id: 0, name: 'Select Level', parentId: 0, url: 'default.html'},
   { id: 1, name: 'Simply Square', parentId: 1, url: `${dir}01-Simply-Square.html`},
   { id: 2, name: 'Carrom', parentId: 1, url: `${dir}02-Carrom.html`},
   { id: 3, name: '', parentId: 1, url: '' },
   { id: 4, name: '', parentId: 1, url: '' },
   { id: 5, name: '', parentId: 1, url: '' },
   { id: 6, name: '', parentId: 1, url: '' },
   { id: 7, name: '', parentId: 1, url: '' },
   { id: 8, name: '', parentId: 1, url: '' },
   { id: 9, name: '', parentId: 1, url: '' },
   { id: 10, name: '', parentId: 1, url: '' },
   { id: 11, name: '', parentId: 1, url: '' },
   { id: 12, name: '', parentId: 1, url: '' },
   { id: 13, name: '', parentId: 2, url: '' },  
   { id: 14, name: '', parentId: 2, url: '' },
   { id: 15, name: '', parentId: 2, url: '' },
   { id: 16, name: '', parentId: 2, url: '' },
   { id: 17, name: '', parentId: 2, url: '' },
   { id: 18, name: '', parentId: 2, url: '' },
   { id: 19, name: '', parentId: 3, url: '' },
   { id: 20, name: '', parentId: 3, url: '' },
   { id: 21, name: '', parentId: 4, url: '' },
   { id: 22, name: '', parentId: 4, url: '' },
   { id: 23, name: '', parentId: 4, url: '' },
   { id: 24, name: '', parentId: 4, url: '' },
   { id: 25, name: '', parentId: 4, url: '' },
   { id: 26, name: '', parentId: 4, url: '' },
   { id: 27, name: '', parentId: 4, url: '' },
   { id: 28, name: '', parentId: 4, url: '' },
   { id: 29, name: '', parentId: 5, url: '' }, 
   { id: 30, name: '', parentId: 5, url: '' },
   { id: 31, name: '', parentId: 6, url: '' }, 
   { id: 32, name: '', parentId: 6, url: '' },
   { id: 33, name: '', parentId: 7, url: '' },
   { id: 34, name: '', parentId: 7, url: '' },
   { id: 35, name: '', parentId: 7, url: '' },
   { id: 36, name: '', parentId: 7, url: '' },
   { id: 37, name: '', parentId: 7, url: '' },
   { id: 38, name: '', parentId: 7, url: '' },
   { id: 39, name: '', parentId: 7, url: '' },
   { id: 40, name: '', parentId: 7, url: '' },
   { id: 41, name: '', parentId: 7, url: '' },
   { id: 42, name: '', parentId: 8, url: '' },
   { id: 43, name: '', parentId: 8, url: '' },
   { id: 44, name: '', parentId: 8, url: '' },
   { id: 45, name: '', parentId: 9, url: '' },
   { id: 46, name: '', parentId: 9, url: '' },
   { id: 47, name: '', parentId: 10, url: '' },
   { id: 48, name: '', parentId: 10, url: '' },
   { id: 49, name: '', parentId: 10, url: '' },
   { id: 50, name: '', parentId: 10, url: '' },
   { id: 51, name: '', parentId: 10, url: '' },
   { id: 52, name: '', parentId: 10, url: '' },
   { id: 53, name: '', parentId: 11, url: '' },
   { id: 54, name: '', parentId: 11, url: '' },
   { id: 55, name: '', parentId: 11, url: '' },
   { id: 56, name: '', parentId: 11, url: '' },
   { id: 57, name: '', parentId: 11, url: '' },
   { id: 58, name: '', parentId: 11, url: '' },
   { id: 59, name: '', parentId: 11, url: '' },
   { id: 60, name: '', parentId: 11, url: '' },
   { id: 61, name: '', parentId: 12, url: '' },
   { id: 62, name: '', parentId: 12, url: '' },
   { id: 63, name: '', parentId: 12, url: '' },
   { id: 64, name: '', parentId: 12, url: '' },
   { id: 65, name: '', parentId: 12, url: '' },
   { id: 66, name: '', parentId: 12, url: '' },
   { id: 67, name: '', parentId: 12, url: '' },
   { id: 68, name: '', parentId: 12, url: '' },
   { id: 69, name: '', parentId: 13, url: '' },
   { id: 70, name: '', parentId: 13, url: '' },
   { id: 71, name: '', parentId: 13, url: '' },
   { id: 72, name: '', parentId: 13, url: '' },
   { id: 73, name: '', parentId: 13, url: '' },
   { id: 74, name: '', parentId: 13, url: '' },
   { id: 75, name: '', parentId: 13, url: '' },
   { id: 76, name: '', parentId: 13, url: '' },
   { id: 77, name: '', parentId: 14, url: '' },
   { id: 78, name: '', parentId: 14, url: '' },
   { id: 79, name: '', parentId: 14, url: '' },
   { id: 80, name: '', parentId: 14, url: '' },
   { id: 81, name: '', parentId: 15, url: '' },
   { id: 82, name: '', parentId: 15, url: '' },
   { id: 83, name: '', parentId: 15, url: '' },
   { id: 84, name: '', parentId: 15, url: '' },
   { id: 85, name: '', parentId: 15, url: '' },
   { id: 86, name: '', parentId: 15, url: '' },
   { id: 87, name: '', parentId: 15, url: '' },
   { id: 88, name: '', parentId: 15, url: '' },
   { id: 89, name: '', parentId: 16, url: '' },
   { id: 90, name: '', parentId: 16, url: '' },
   { id: 91, name: '', parentId: 16, url: '' },
   { id: 92, name: '', parentId: 16, url: '' },
   { id: 93, name: '', parentId: 16, url: '' },
   { id: 94, name: '', parentId: 16, url: '' },
   { id: 95, name: '', parentId: 16, url: '' },
   { id: 96, name: '', parentId: 16, url: '' },
   { id: 97, name: '', parentId: 17, url: '' },
   { id: 98, name: '', parentId: 17, url: '' },
   { id: 99, name: '', parentId: 17, url: '' },
   { id: 100, name: '', parentId: 17, url: '' },
   { id: 101, name: '', parentId: 18, url: '' },
   { id: 102, name: '', parentId: 18, url: '' },
   { id: 103, name: '', parentId: 18, url: '' },
   { id: 104, name: '', parentId: 18, url: '' },
   { id: 105, name: '', parentId: 18, url: '' },
   { id: 106, name: '', parentId: 18, url: '' },
   { id: 107, name: '', parentId: 18, url: '' },
   { id: 108, name: '', parentId: 18, url: '' },
   { id: 109, name: '', parentId: 19, url: '' },
   { id: 110, name: '', parentId: 19, url: '' },
   { id: 111, name: '', parentId: 19, url: '' },
   { id: 112, name: '', parentId: 19, url: '' },
   { id: 113, name: '', parentId: 19, url: '' },
   { id: 114, name: '', parentId: 19, url: '' },
   { id: 115, name: '', parentId: 19, url: '' },
   { id: 116, name: '', parentId: 19, url: '' },
   { id: 117, name: '', parentId: 20, url: '' },
   { id: 118, name: '', parentId: 20, url: '' },
   { id: 119, name: '', parentId: 20, url: '' },
   { id: 120, name: '', parentId: 20, url: '' },
   { id: 121, name: '', parentId: 20, url: '' },
   { id: 122, name: '', parentId: 20, url: '' },
   { id: 123, name: '', parentId: 20, url: '' },
   { id: 124, name: '', parentId: 20, url: '' },
   { id: 125, name: '', parentId: 21, url: '' },
   { id: 126, name: '', parentId: 21, url: '' },
   { id: 127, name: '', parentId: 21, url: '' },
   { id: 128, name: '', parentId: 21, url: '' },
   { id: 129, name: '', parentId: 21, url: '' },
   { id: 130, name: '', parentId: 21, url: '' },
   { id: 131, name: '', parentId: 21, url: '' },
   { id: 132, name: '', parentId: 21, url: '' },













]
export { battle, play }